### ISSUE TITLE
Chapters

### ISSUE THREAD

**Issue by fakerybakery** [voussoir/epubfile#1]
Hi,
Is it possible to extract chapters from the EPUB?
Thanks!

**Comment by voussoir** [comment]
Hi, this depends on the layout of your book and what you mean by "chapter". As far as the EPUB format is concerned, you have files in the manifest and you have navpoints in the table of contents. With epubfile you can get all manifest items with `get_manifest_items`, or just get the text files with `get_texts`. You can get the nav with `get_nav`, but after that you'll have to deal with the BeautifulSoup object yourself to open the right file and pull out the anchored element.

The definition of "chapter" is not really clear. A lot of books will use nested levels of h1, h2, h3 to create hierarchies of sections, subsections, chapters, parts... it's up to the human how they want to organize the book and what to call each thing. A lot of books have headings that just say "III" rather than "Chapter 3". So I would say there is no specific answer to this.

If you want to assume that your book is one chapter per file, you can:

```Python
for text_id in book.get_texts():
    text_content = book.read_file(text_id)
    ... # do whatever you want with the text
```

I can see from your profile that you're interested in AI stuff and I'd guess you're trying to extract a whole bunch of book text. I feel like I should warn you that epubfile is just hobby code so I don't know if you might run into books that crash epubfile, either due to their being malformed or my not handling an edge case!

**Comment by fakerybakery** [comment]
Ah, thanks for the info! I was actually interested in extracting chapters from Gutenberg books to run through a TTS system. Again, thanks for creating this amazing tool!
